# 异常的捕获及处理

+ [`什么是异常?`](#什么是异常)
  + [`不产生异常的代码`](#不产生异常的代码)
  + [`产生异常的代码`](#产生异常的代码)
+ [`如何处理异常？`](#如何处理异常)
  + [`应用异常处理格式 —— 使用 try、catch 语句块`](#应用异常处理格式)
  + [`输出异常的完整信息`](#输出异常的完整信息)
  + [`使用完整异常处理结构  —— 添加 finally 语句块`](#使用完整异常处理结构)
+ [`异常的处理流程（核心）`](#异常的处理流程)
  + [`使用Exception处理异常`](#使用exception处理异常)
  + [`错误的异常捕获顺序`](#错误的异常捕获顺序)
+ [`throws 关键字 —— 抛出异常`](#throws关键字)
  + [`如何使用 throws`](#如何使用throws)
  + [`手工抛出异常`](#手工抛出异常)
+ [`RuntimeException类`](#runtimeexception类)
  + [`使用 parseInt() 方法不处理异常`](#使用parseint方法不处理异常) 
+ [`自定义异常`](#自定义异常)
  + [`定义 MyException`](#定义myexception)

## 什么是异常

### 不产生异常的代码

```java
public class TestDemo {
        static void main(String args[]) {
        System.out.println("1. 除法计算开始。");
        System.out.println("2. 除法计算：" + (10 / 2));
        System.out.println("3. 除法计算结束。");
    }
}
/*
1. 除法计算开始。
2. 除法计算：5
3. 除法计算结束。
*/
```

### 产生异常的代码

+ 以0为除数 
+ java.lang.ArithmeticException: / by zero at TestDemo.main(TestDemo.java:4)

```java
public class TestDemo {
        public static void main(String args[]) {
        System.out.println("1. 除法计算开始。") ;
        System.out.println("2. 除法计算：" + (10 / 0)) ; // → 此处产生异常
        // 出现异常并且没有正确处理后，异常之后的语句将不再执行
        System.out.println("3. 除法计算结束。") ;
    }
}
/*
Exception in thread "main" java.lang.ArithmeticException: / by zero
at TestDemo.main(TestDemo.java:4)
1. 除法计算开始。
*/
```

## 如何处理异常

### 应用异常处理格式

```java
public class TestDemo {
    public static void main(String args[]) {
        System.out.println("1. 除法计算开始。");
        try {
        System.out.println("2. 除法计算：" + (10 / 0)); // 此处产生异常
        // 异常产生之后的语句将不再执行，此处在try中产生异常，所以下面的输出不会执行 
        System.out.println("中北大学安卓实验室");
        } catch (ArithmeticException e) { // 处理算术异常
        System.out.println("******** 出现异常了 *********");
        }
        System.out.println("3. 除法计算结束。");
    }
}
/*
1. 除法计算开始。
******** 出现异常了 *********
3. 除法计算结束。
*/
```

### 输出异常的完整信息

```java
public class TestDemo {
    public static void main(String args[]) {
        System.out.println("1. 除法计算开始。");
        try {
        System.out.println("2. 除法计算：" + (10 / 0));	// 此处产生异常
        // 异常产生之后的语句将不再执行，此处在try中产生异常，所以下面的输出不会执行 
        System.out.println("中北大学安卓实验室");
        } catch (ArithmeticException e) { // 处理算术异常
            e.printStackTrace(); // 输出异常的完整信息
        }
        System.out.println("3. 除法计算结束。");
    }
}
/*
1. 除法计算开始。
java.lang.ArithmeticException: / by zero
3. 除法计算结束。
at TestDemo.main(TestDemo.java:5)
*/
```

### 使用完整异常处理结构

```java

public class TestDemo {
    public static void main(String args[]) {
        System.out.println("1. 除法计算开始。");
        try {
            System.out.println("2. 除法计算：" + (10 / 0)); // 此处产生异常
            // 异常产生之后的语句将不再执行，此处在try中产生异常，所以下面的输出不会执行
            System.out.println("中北大学安卓实验室");
        } catch (ArithmeticException e) { // 处理算术异常
            e.printStackTrace(); // 输出异常的完整信息
        } finally {
            System.out.println("### 不管是否出现异常我都执行！") ;
        }
        System.out.println("3. 除法计算结束。");
    }
}
/*
1. 除法计算开始。
	at TestDemo.main(TestDemo.java:6)
### 不管是否出现异常我都执行！
3. 除法计算结束。
*/
```

## 异常的处理流程

### 使用exception处理异常

```java
public class TestDemo {
    public static void main(String args[]) {
        System.out.println("1. 除法计算开始。");
        try {
            int x = Integer.parseInt(args[0]); // 接收参数并且转型
            int y = Integer.parseInt(args[1]); // 接收参数并且转型
            System.out.println("2. 除法计算：" + (x / y));	// 此处产生异常
            // 异常产生之后的语句将不再执行，此处在try中产生异常，所以下面的输出不会执行
            System.out.println("中北大学安卓实验室");
        } catch (Exception e) { // 处理所有异常类型
            e.printStackTrace();
        } finally {
            System.out.println("### 不管是否出现异常我都执行！") ;
        }
        System.out.println("3. 除法计算结束。");
    }
}

/*
java.lang.ArrayIndexOutOfBoundsException: 0
1. 除法计算开始。
at TestDemo.main(TestDemo.java:5)
### 不管是否出现异常我都执行！
3. 除法计算结束。
*/
```

### 错误的异常捕获顺序

+ 处理过的异常不可再被处理

```java
public class TestDemo {
    public static void main(String args[]) {
        System.out.println("1. 除法计算开始。");
        try {
            int x = Integer.parseInt(args[0]); // 接收参数并且转型
            int y = Integer.parseInt(args[1]); // 接收参数并且转型
            System.out.println("2. 除法计算：" + (x / y));	// 此处产生异常
            // 异常产生之后的语句将不再执行，此处在try中产生异常，所以下面输出不会执行
            System.out.println("中北大学安卓实验室");
        } catch (Exception e) { // 处理所有异常类型
            e.printStackTrace();
        } catch (ArithmeticException e) { // 此处无法处理，Exception已处理完
            e.printStackTrace();
        } finally {
            System.out.println("### 不管是否出现异常我都执行！") ;
        }
        System.out.println("3. 除法计算结束。");
    }
}
```

+ 报错

```java
Error:(12, 11) java: 已捕获到异常错误java.lang.ArithmeticException
```

## throws关键字

### 如何使用throws

```java
class MyMath {
    public static int div(int x, int y) throws Exception { // 此方法不处理异常
        return x / y;
    }
}
public class TestDemo {
    public static void main(String args[]) {
        try { // div()方法抛出异常，必须明确进行异常处理
            System.out.println(MyMath.div(10, 2));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
/*
5
*/
```

### 手工抛出异常

+ 直接抛出一个自定义的异常类对象

```java
public class TestDemo {
    public static void main(String args[]) {
        try { // 直接抛出一个自定义的异常类对象
            throw new Exception("自己定义的异常！");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
/*
java.lang.Exception: 自己定义的异常！at TestDemo.main(TestDemo.java:4)
*/
```

## runtimeexception类

### 使用parseint方法不处理异常

```java
public class TestDemo {
    public static void main(String args[]) {
        int temp = Integer.parseInt("100"); // 直接将字符串变为int型
        System.out.println(temp);
    }
}
/*
100
*/
```

## 自定义异常

### 定义myException

```java
class MyException extends Exception { // 此异常类要强制处理
    public MyException(String msg) {
        super(msg); // 调用父类构造
    }
}
public class TestDemo {
    public static void main(String args[]) {
        int num = 20;
        try {
            if (num > 10) { // 出现了错误，应该产生异常
                throw new MyException("数值传递的过大！");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
/*
MyException: 数值传递的过大！ at TestDemo.main(TestDemo.java:11)
*/
```